### ISSUE TITLE
input 컴포넌트 마크업, 스타일링

### ISSUE THREAD

**Issue by YSP97** [FRONTENDSCHOOL10/5jorago-vanilla-project#11]
![image](https://github.com/FRONTENDSCHOOL10/5jorago-vanilla-project/assets/140301763/2416b132-417d-4586-9ed1-3dc65ca91f3a)
✅ 반응형 고려해주세요!!

**Comment by Gomyeunghan** [comment]
충돌로 인해, 새로운 이슈 발행
